//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int AlbumID { get; set; }
        public string TenAlbum { get; set; }
        public string ChuThich { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AlbumCha { get; set; }
    }
}
